### PR TITLE
feat: Allow port option for launching chromium browser

### PR DESCRIPTION
**Pull request by dever23b**
This suggestion allows us to specify a port when launching Chrome.  While we can easily add the "remote-debugging-port" option to vite.config.ts, the option doesn't get picked up by web-ext and results in a connection failure error shortly after launching a debugging session.

In absence of a port option, web-ext chooses a random port when launching .  By specifying a specific port, it makes it easier to attach to the spawned browser with a debugger during testing.

### CODE REVIEW

**Comment by dever23b** [comment]
To clarify: I want to be able to create a debug workflow in my IDE (VS Code) to attach to the browser that gets spawned.  The random ports make this more tedious, because I have to find the random port each time I spawn the browser and update the launch config for the debug environment in VS Code.  The underlying chrome-launch dependency that this code uses supports specifying a specific port, so this PR bridges that gap for an easier debugging experience.

**Review by aklinker1 — APPROVED** [review]
Good PR, thanks. You may also want to open a PR on the original repo, [`mozilla/web-ext`](https://github.com/mozilla/web-ext)

**Comment by aklinker1** [comment]
Released in https://github.com/wxt-dev/web-ext-run/releases/tag/web-ext-run-v0.2.1

**Comment by dever23b** [comment]
> Good PR, thanks. You may also want to open a PR on the original repo, [`mozilla/web-ext`](https://github.com/mozilla/web-ext)

Thank you.  Good idea.  I'll work on that soon.

**Pull request merged**
